name: Build & deploy to linode

on:
  push:
    branches: [ backToLinode ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout

    - uses: actions/setup-dotnet@v1
      name: Setup dotnet
      with:
        dotnet-version: '5.0'

    - run: dotnet publish -r linux-x64 -c Release -o out -p:PublishSingleFile=true -p:PublishReadyToRun=true --self-contained false Hysite.Web

    - name: tar hysite
      run: |
        tar czf hysite.tar.gz out/

    - run: ls out

    - name: Transfer to linode with scp 
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.LINODE_HOST }}
        username: ${{ secrets.LINODE_USERNAME }}
        password: ${{ secrets.LINODE_PASSWORD }}
        source: "hysite.tar.gz"
        target: ""
