name: Build docker image, push to dockerhub, deploy on linode

on:
  push:
    branches: [ backToLinode, master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: hyston/hysite:latest
          build-args: |
            HYSITE_VERSION=${{ github.sha }}

      - run: docker push hyston/hysite:latest

      - name: Restart hysite 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USERNAME }}
          password: ${{ secrets.LINODE_PASSWORD }}
          script: |
            docker stop $(docker ps -aq)
            docker pull hyston/hysite:latest
            docker run --rm -d -p 80:80 -v /root/logs:/app/logs hyston/hysite:latest
