name: Build docker image, push to dockerhub, deploy on linode

on:
  push:
    branches: [ backToLinode, master, '2023' ]

jobs:

  testJob:

    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Test with the dotnet CLI
        run: dotnet test

  buildJob:

    runs-on: ubuntu-latest
    needs: testJob

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: hyston/hysite:latest
          build-args: |
            HYSITE_VERSION=${{ github.sha }}
            READER_TOKEN=${{ secrets.READER_TOKEN }}

      - run: docker push hyston/hysite:latest

      - name: Restart hysite 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USERNAME }}
          password: ${{ secrets.LINODE_PASSWORD }}
          script: |
            docker stop $(docker ps -aq)
            docker pull hyston/hysite:latest
            docker run --rm -d -p 80:80 -p 443:443 \
            -v /root/logs:/app/logs \
            -v /etc/letsencrypt/prod/hyston.blog:/app/cert \
            -e ASPNETCORE_Kestrel__Certificates__Default__Path=/app/cert/fullchain.pem \
            -e ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/app/cert/privkey.pem \
            hyston/hysite:latest