name: Build & deploy to linode

on:
  push:
    branches: [ backToLinode ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout

    - uses: actions/setup-dotnet@v1
      name: Setup dotnet
      with:
        dotnet-version: '5.0'

    - run: dotnet publish -r linux-x64 -c Release -o out -p:PublishSingleFile=true -p:PublishTrimmed=true -p:PublishReadyToRun=true --self-contained false Hysite.Web

    - run: ls out

    


    


