name: Shh into linode

on:
  push:
    branches: [ backToLinode ]

jobs:

  build:

    runs-on: ubuntu-latest

    - name: Restart hysite 
            uses: appleboy/ssh-action@master
            with:
              host: ${{ secrets.LINODE_HOST }}
              username: ${{ secrets.LINODE_USERNAME }}
              password: ${{ secrets.LINODE_PASSWORD }}
              script: |
                docker stop $(docker ps -aq)
                docker pull hyston/hysite:latest
                docker run --rm -d -p 80:80 -v /root/logs:/app/logs hyston/hysite:latest
